In [5]:
# 1.	Write a Python Program to Add Two Matrices?
import numpy as np
mat1 = np.array([[6, 2, 7], [1, 5, 7], [2, 8, 8]])
mat2 = np.array([[9, 8, 7], [8, 5, 4], [7, 2, 1]])
result = np.add(mat1,mat2)
print(result)

[[15 10 14]
 [ 9 10 11]
 [ 9 10  9]]


In [7]:
# 2.	Write a Python Program to Multiply Two Matrices?
mat1 = np.array([[5, 8], [3, 6]])
mat2 = np.array([[5, 8], [9, 8]])
result = np.dot(mat1, mat2)
print(result)

[[ 97 104]
 [ 69  72]]


In [8]:
# 3.	Write a Python Program to Transpose a Matrix?

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.transpose(matrix)
print(result)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
# 4.	Write a Python Program to Sort Words in Alphabetic Order?

my_str = "Hello this Is an Example With cased letters"

# breakdown the string into a list of words
words = [word.lower() for word in my_str.split()]

# sort the list
words.sort()

# display the sorted words

print("The sorted words are:")
for word in words:
   print(word)


The sorted words are:
an
cased
example
hello
is
letters
this
with


In [10]:
# 5.	Write a Python Program to Remove Punctuation From a String?
import string

def remove_punctuation(input_string):
    translator = str.maketrans('', '', string.punctuation)
    no_punct = input_string.translate(translator)
    return no_punct

input_string = "Hello, World! How are you? I'm fine, thank you."
print(remove_punctuation(input_string))


Hello World How are you Im fine thank you
